-- DROP VIEW ORCL
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW UV_QCSUBHEADING';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- ORA-00942: table or view does not exist
            RAISE;
        END IF;
END;
COMMIT;

-- CREATE OR REPLACE VIEW ORCL
CREATE OR REPLACE FORCE VIEW UV_QCSUBHEADING
(
    CASE_KEY,
    SUBHEADING
)
AS
    SELECT CASE_KEY,
        MAX(RECEIVED_DATE) as SUBHEADING
    FROM TV_LABSUB 
    GROUP BY CASE_KEY;
COMMIT;

-- DROP VIEW MSQL
DROP VIEW IF EXISTS UV_QCSUBHEADING;

-- CREATE VIEW MSQL
CREATE VIEW UV_QCSUBHEADING
(
    CASE_KEY,
    SUBHEADING
)
AS
SELECT 
    CASE_KEY,
    MAX(RECEIVED_DATE) AS SUBHEADING
FROM TV_LABSUB 
GROUP BY CASE_KEY;