SELECT 
    I.EVIDENCE_CONTROL_NUMBER, 
    I.CASE_KEY, 
    I.LAB_CASE_SUBMISSION, 
    S.COMMAND_VOUCHER AS VOUCHER, 
    I.THIRD_PARTY_BARCODE, 
    T.DESCRIPTION AS ITEM_TYPE, 
    P.DESCRIPTION AS PACKAGING_CODE,   
    I.ITEM_DESCRIPTION,  
    CO.CONTAINER_DESCRIPTION,   
    I.LAB_ITEM_NUMBER, 
    I.DEPARTMENT_ITEM_NUMBER, 
    C.DESCRIPTION + '-' + L.DESCRIPTION AS LOCATION, 
    R.DESCRIPTION AS PROCESS, 
    I.ITEM_SORT 
FROM TV_LABITEM AS I   
LEFT OUTER JOIN TV_CONTAINER AS CO ON     I.CONTAINER_KEY = CO.CONTAINER_KEY   
LEFT OUTER JOIN TV_CUSTCODE AS C ON C.CUSTODY_TYPE = I.CUSTODY_OF       
LEFT OUTER JOIN TV_CUSTLOC AS L ON L.CUSTODY_CODE = I.CUSTODY_OF AND L.LOCATION = I.LOCATION     
LEFT OUTER JOIN   TV_ITEMTYPE AS T ON T.ITEM_TYPE = I.ITEM_TYPE   
LEFT OUTER JOIN TV_PACKTYPE AS P ON P.PACKAGING_CODE = I.PACKAGING_CODE   
LEFT OUTER JOIN TV_PROCESS AS R ON R.PROCESS_TYPE = I.PROCESS     
LEFT OUTER JOIN TV_LABSUB AS   S ON S.CASE_KEY = I.CASE_KEY AND S.SUBMISSION_NUMBER = I.LAB_CASE_SUBMISSION     
WHERE  I.CASE_KEY = <&>CASE_KEY</&>  ORDER BY I.LAB_CASE_SUBMISSION, I.ITEM_SORT, I.THIRD_PARTY_BARCODE