-- Ticket #1069 - Create sub-item on new LABITEM record

CREATE TRIGGER [dbo].[LABITEM_CREATE_SUBITEM] ON [dbo].[TV_LABITEM] AFTER INSERT AS

BEGIN

    SET NOCOUNT ON;

    -- Insert sub-item into TV_LABITEM if AUTO_CREATE_SUBITEM is 'T'
    INSERT INTO TV_LABITEM (PARENT_ECN, ITEM_DESCRIPTION, ITEM_TYPE)
    SELECT i.EVIDENCE_CONTROL_NUMBER, ITEM_DESCRIPTION, i.ITEM_TYPE
    FROM inserted i
    JOIN TV_ITEMTYPE t ON i.ITEM_TYPE = t.ITEM_TYPE
    WHERE t.AUTO_CREATE_SUBITEM = 'T';

    -- Insert audit log
    INSERT INTO TV_AUDITLOG (LOG_STAMP, TIME_STAMP, USER_ID, PROGRAM, CODE, SUB_CODE, ERROR_LEVEL, ADDITIONAL_INFORMATION)
    SELECT CURRENT_TIMESTAMP, GETDATE(), SYSTEM_USER, 'LABITEM_CREATE_SUBITEM', '7000', '24', '0', 'Subitem created for ITEM_ID: ' + CAST(i.EVIDENCE_CONTROL_NUMBER AS NVARCHAR(50))
    FROM inserted i
    JOIN TV_ITEMTYPE t ON i.ITEM_TYPE = t.ITEM_TYPE
    WHERE t.AUTO_CREATE_SUBITEM = 'T';
END;