DELETE FROM TV_ACNITEM WHERE ACN_ITEM_CODE = 'ITMRTT'
INSERT INTO ACNITEM (
  'ACN Item Code',	
  'ACN Type Code',	
  'Prompt',	
  'Description',	
  'Response Type',	
  'Summary Query',	
  'Detail Query',	
  'RPT Format Name',	
  'Action Page',	
  'Action View'
)
VALUES(
  'ITMRTT',
  'A',  	
  'Items Ready To Transfer To VCSO Property',
  'Items Ready To Transfer To VCSO Property',	
  '1',	
  'SELECT COUNT(DISTINCT LI.EVIDENCE_CONTROL_NUMBER) AS CNT FROM TV_LABITEM LI  INNER JOIN TV_LABCASE LC ON LI.CASE_KEY = LC.CASE_KEY  LEFT OUTER JOIN TV_ITEMTYPE IT ON LI.ITEM_TYPE = IT.ITEM_TYPE  INNER JOIN TV_CUSTCODE CC ON LI.CUSTODY_OF = CC.CUSTODY_TYPE AND LC.DEPARTMENT_CODE = CC.DEPARTMENT_CODE  INNER JOIN TV_SRDETAIL SRD ON LI.EVIDENCE_CONTROL_NUMBER = SRD.EVIDENCE_CONTROL_NUMBER  INNER JOIN TV_LABEXAM LE ON SRD.EXAM_KEY = LE.EXAM_KEY  WHERE SRD.STATUS_CODE = '3' AND   EXISTS (SELECT * FROM TV_ANALYST AN  WHERE LC.DEPARTMENT_CODE = AN.DEPARTMENT_CODE AND AN.ANALYST = %USER%)',	
  'SELECT LI.EVIDENCE_CONTROL_NUMBER AS ACTION_KEY, LC.DEPARTMENT_CASE_NUMBER AS "Agency Case#", LI.DEPARTMENT_ITEM_NUMBER AS "Agency Item#", LI.LAB_ITEM_NUMBER AS "Lab Item#",   IT.DESCRIPTION AS "Item Type", LI.ITEM_DESCRIPTION AS "Item Description", SR.SECTIONS AS "Approved Sections"  FROM TV_LABITEM LI  INNER JOIN TV_LABCASE LC ON LI.CASE_KEY = LC.CASE_KEY  INNER JOIN TV_CUSTCODE CC ON LI.CUSTODY_OF = CC.CUSTODY_TYPE AND LC.DEPARTMENT_CODE = CC.DEPARTMENT_CODE  LEFT OUTER JOIN TV_ITEMTYPE IT ON LI.ITEM_TYPE = IT.ITEM_TYPE  INNER JOIN (SELECT LI1.EVIDENCE_CONTROL_NUMBER,                 STUFF((SELECT DISTINCT (',' + SRD.SECTION) FROM TV_SRDETAIL SRD INNER JOIN TV_LABEXAM LE ON SRD.EXAM_KEY = LE.EXAM_KEY WHERE SRD.STATUS_CODE = '3' AND                 SRD.EVIDENCE_CONTROL_NUMBER = LI1.EVIDENCE_CONTROL_NUMBER                FOR XML PATH('')), 1,1,'') AS SECTIONS FROM TV_LABITEM LI1  ) SR ON LI.EVIDENCE_CONTROL_NUMBER = SR.EVIDENCE_CONTROL_NUMBER AND SR.SECTIONS IS NOT NULL  WHERE EXISTS (SELECT * FROM TV_ANALYST AN  WHERE LC.DEPARTMENT_CODE = AN.DEPARTMENT_CODE AND AN.ANALYST = %USER%)    ORDER BY LC.DEPARTMENT_CASE_NUMBER, LI.ITEM_SORT',  	
  'AI_ITMRTT',	
  'ACTIONITEMS',	
  'TV_TEMPLIST'
)

-- Ticket#????? - Can I get this tonight. We really need this change for tomorrow

UPDATE TV_ACNITEM SET ACTION_VIEW = 'TV_TEMPLIST' WHERE ACN_ITEM_CODE = 'ITMRTT';