select * from TV_ANALYST
where ANALYST = 'WILLIE'

select * from TV_TEMPLIST
where EVIDENCE_CONTROL_NUMBER = '4379'

select * from TV_ACNGROUP
select * from TV_ACNNOTIFY
select * from TV_ACNTYPE
select * from TV_ACNRTYP
select * from TV_ACNITEM

select * from TV_ACNITEM

select * from TV_ACNGLINK

select ANALYST, ACN_GROUP_CODE from TV_ANALYST
where ANALYST = 'MIKE'

SELECT L.ACN_ITEM_CODE, ACN_TYPE_CODE, PROMPT, ACTION_PAGE, SUMMARY_QUERY, SEQUENCE FROM TV_ACNGLINK L
INNER JOIN TV_ACNITEM I ON L.ACN_ITEM_CODE = I.ACN_ITEM_CODE WHERE ACN_GROUP_CODE IN ('LGMT','*')
ORDER BY SEQUENCE


SELECT COUNT(*) FROM TV_ACT_QAISSUE WHERE STATUS IS NULL
SELECT COUNT(E.CASE_KEY) CNT FROM TV_LABEXAM E WHERE E.ROUTE_TO = 'MIKE'

SELECT COUNT(DISTINCT LI.EVIDENCE_CONTROL_NUMBER) AS CNT FROM TV_LABITEM LI
INNER JOIN TV_LABCASE LC ON LI.CASE_KEY = LC.CASE_KEY
LEFT OUTER JOIN TV_ITEMTYPE IT ON LI.ITEM_TYPE = IT.ITEM_TYPE
INNER JOIN TV_CUSTCODE CC ON LI.CUSTODY_OF = CC.CUSTODY_TYPE AND LC.DEPARTMENT_CODE = CC.DEPARTMENT_CODE
INNER JOIN TV_SRDETAIL SRD ON LI.EVIDENCE_CONTROL_NUMBER = SRD.EVIDENCE_CONTROL_NUMBER
INNER JOIN TV_LABEXAM LE ON SRD.EXAM_KEY = LE.EXAM_KEY
WHERE SRD.STATUS_CODE = '3' AND 
EXISTS (SELECT * FROM TV_ANALYST AN  WHERE LC.DEPARTMENT_CODE = AN.DEPARTMENT_CODE AND AN.ANALYST = 'WICK')