INSERT INTO CHEMSETUP ("Chem Setup Key", "Chem Category", "URL", "Description")
VALUES (31, 'D', 'TAB6Component.aspx', 'Component');

INSERT INTO CHEMSETUP ("Chem Setup Key", "Chem Category", "URL", "Description")
VALUES (32, 'D', 'TAB7ServHistory.aspx', 'Service History');


INSERT INTO CHEMPANEL ("Chem Setup Key", "Panel Name", "Remove From Screen", "User")
VALUES (31, 'CHEM_C_COMPONENT', 'F', 2);

INSERT INTO CHEMPANEL ("Chem Setup Key", "Panel Name", "Remove From Screen", "User")
VALUES (32, 'CHEM_C_SERVICEHISTORY', 'F', 1);


UPDATE CHEMPANEL
SET "Panel Name" = 'CHEM_D_COMPONENT'
WHERE "Chem Setup Key" = 31;

UPDATE CHEMPANEL
SET "Panel Name" = 'CHEM_D_SERVICEHISTORY'
WHERE "Chem Setup Key" = 32;


DELETE FROM TV_DBGRIDHD WHERE GRID_NAME = 'CHEMINV_COMPONENTS';
INSERT INTO TV_DBGRIDHD (GRID_NAME,SQL_STRING,DESCRIPTION,PANEL_NAME,GRID_WIDTH,GRID_HEIGHT,RECORDS_PER_PAGE,USES_SCROLLBAR) VALUES ('CHEMINV_COMPONENTS','SELECT CR.SUB_CHEM_CONTROL_NUMBER, CI.BARCODE, CI.ASSET_NAME, CI.LOT_NUMBER, FORMATDATE(CI.EXPIRATION_DATE) AS "EXPIRATION_DATE", CR.AMOUNT, CR.UNITS FROM TV_CHEMREAGENT CR LEFT OUTER JOIN TV_CHEMINV CI ON CR.SUB_CHEM_CONTROL_NUMBER = CI.CHEM_CONTROL_NUMBER WHERE CR.CHEM_CONTROL_NUMBER = <&>CHEM_CONTROL_NUM</&>','Chemical Inventory Components',NULL,NULL,NULL,NULL,NULL);


DELETE FROM TV_DBGRIDDL WHERE GRID_NAME = 'CHEMINV_COMPONENTS';
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('CHEMINV_COMPONENTS','AMOUNT','Amount','80','F','5',NULL,NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('CHEMINV_COMPONENTS','ASSET_NAME','Asset Name','200','F','2',NULL,NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('CHEMINV_COMPONENTS','BARCODE','Barcode','100','F','1',NULL,NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('CHEMINV_COMPONENTS','EXPIRATION_DATE','Expiry Date','100','F','4',NULL,NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('CHEMINV_COMPONENTS','LOT_NUMBER','Lot #','80','F','3',NULL,NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('CHEMINV_COMPONENTS','UNITS','Units','100','F','6',NULL,NULL,NULL);

-- === Insert into TV_CHEMSETUP ===
INSERT INTO CHEMSETUP ("Chem Setup Key", "Chem Category", "URL", "Description") VALUES (33, 'C', 'TAB10Issues.aspx', 'Issue');
INSERT INTO CHEMSETUP ("Chem Setup Key", "Chem Category", "URL", "Description") VALUES (34, 'C', 'TAB11Receipts.aspx', 'Receive');
INSERT INTO CHEMSETUP ("Chem Setup Key", "Chem Category", "URL", "Description") VALUES (35, 'C', 'TAB6Component.aspx', 'Component');
INSERT INTO CHEMSETUP ("Chem Setup Key", "Chem Category", "URL", "Description") VALUES (36, 'C', 'TAB7ServHistory.aspx', 'Service History');

-- === Insert into CHEMPANEL ===
INSERT INTO CHEMPANEL ("Chem Setup Key", "Panel Name", "Remove From Screen", "User") VALUES (33, 'CHEM_C_ISSUES', 'F', 1);
INSERT INTO CHEMPANEL ("Chem Setup Key", "Panel Name", "Remove From Screen", "User") VALUES (34, 'CHEM_C_RECEIPTS', 'F', 1);
INSERT INTO CHEMPANEL ("Chem Setup Key", "Panel Name", "Remove From Screen", "User") VALUES (35, 'CHEM_C_COMPONENT', 'F', 2);
INSERT INTO CHEMPANEL ("Chem Setup Key", "Panel Name", "Remove From Screen", "User") VALUES (36, 'CHEM_C_SERVICEHISTORY', 'F', 1);

COMMIT;


DELETE FROM TV_DBPANEL WHERE PANEL_NAME = 'CHEM_C_ISSUES';
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','ANALYST','Issuing Analyst','!!!!!!','6','TV_ANALYST',NULL,'CHEM_C_ISSUES','1','T','305','T',NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','EXHAUSTED','Exhausted','CB','8',NULL,NULL,'CHEM_C_ISSUES','2',NULL,NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','DATE_USED','Date/Time','mm/dd/yyyy hh:mm:ss','19',NULL,NULL,'CHEM_C_ISSUES','3','T','140','T',NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','AMOUNT_USED','Quantity (AMOUNT_USED)','9999999999999999999999','22',NULL,'T','CHEM_C_ISSUES','4',NULL,'100','T',NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','RECEIVING_ANALYST','Receiving Analyst','!!!!!!','6','TV_ANALYST',NULL,'CHEM_C_ISSUES','5',NULL,'305',NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','ISSUED_TO_CUSTODY_CODE','Custody','!!!!','4','TV_CUSTCODE',NULL,'CHEM_C_ISSUES','6','T','305','T',NULL,'CUSTODY_TYPE in (SELECT CUSTODY_CODE FROM TV_CUSTLOC WHERE ISSUED_LOCATION = ''T'')');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','ISSUED_TO_LOCATION','Location','!!!!!!!!','8','CV_CUSTLOC',NULL,'CHEM_C_ISSUES','7',NULL,'305','T',NULL,'CUSTODY_CODE = {ISSUED_TO_CUSTODY_CODE} AND ACTIVE = ''T'' AND ISSUED_LOCATION = ''T''');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','COMMENTS','Purpose of Dispensing',NULL,'4000',NULL,NULL,'CHEM_C_ISSUES','8',NULL,'300',NULL,'4',NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','CHEM_CONTROL_NUMBER',NULL,'99999999','8',NULL,'H','CHEM_C_ISSUES','9',NULL,NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','EXAM_KEY',NULL,'99999999','8',NULL,'H','CHEM_C_ISSUES','10',NULL,NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','CASE_KEY',NULL,'99999999','8',NULL,'H','CHEM_C_ISSUES','11',NULL,NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','BATCH_NUMBER',NULL,'99999999','8',NULL,'H','CHEM_C_ISSUES','12',NULL,NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','BEGINNING_WEIGHT','Beginning ''Weight (BEGINNING_WEIGHT)','9999.9999','9',NULL,NULL,'CHEM_C_ISSUES','13',NULL,'100',NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','ENDING_WEIGHT','Ending Weight (ENDING_WEIGHT)','9999.9999','9',NULL,NULL,'CHEM_C_ISSUES','14',NULL,'100',NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMUSE','AMOUNT_USED','Amount Used','9999.9999','99',NULL,NULL,'CHEM_C_ISSUES','15',NULL,'100',NULL,NULL,NULL);


DELETE FROM TV_DBPANEL WHERE PANEL_NAME = 'CHEM_C_RECEIPTS';
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','DATE_RECEIVED','Date/Time','mm/dd/yyyy HH:mm:ss','19',NULL,NULL,'CHEM_C_RECEIPTS','1','T',NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','AMOUNT_RECEIVED','Quantity Received','9999999','7',NULL,NULL,'CHEM_C_RECEIPTS','3',NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','RECEIVED_FROM','Received From','XXXXXX','6','TV_ANALYST',NULL,'CHEM_C_RECEIPTS','4','T',NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','PURCHASE_ORDER','Purchase Order','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX','30',NULL,NULL,'CHEM_C_RECEIPTS','5',NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','RECEIVED_FROM_CUSTODY_CODE','Custody','XXXXXX','6','TV_CUSTCODE',NULL,'CHEM_C_RECEIPTS','6','T','300',NULL,'CUSTODY_TYPE in (SELECT CUSTODY_CODE FROM TV_CUSTLOC WHERE RECEIVED_LOCATION = ''T'')');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','RECEIVED_FROM_LOCATION','Location','XXXXXXXX','8','CV_CUSTLOC',NULL,'CHEM_C_RECEIPTS','7',NULL,'300',NULL,'CUSTODY_CODE = {RECEIVED_FROM_CUSTODY_CODE} AND ACTIVE = ''T'' AND RECEIVED_LOCATION = ''T''');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','COMMENTS','Comments',NULL,'4000',NULL,NULL,'CHEM_C_RECEIPTS','10',NULL,NULL,'8',NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','CHEM_CONTROL_NUMBER',NULL,'99999999','8',NULL,'H','CHEM_C_RECEIPTS','99',NULL,NULL,NULL,NULL);
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MEMO_FIELD_LINES,CODE_CONDITION) VALUES ('TV_CHEMRCPT','BATCH_NUMBER',NULL,'99999999','8',NULL,'H','CHEM_C_RECEIPTS','100',NULL,NULL,NULL,NULL);

DELETE FROM TV_DBPANEL WHERE PANEL_NAME = 'CHEM_C_COMPONENT';
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_CHEMREAGENT','SUB_CHEM_CONTROL_NUMBER','SUB_CHEM_CONTROL_NUMBER','!!!!!!!!!!','10',NULL,'H','CHEM_C_COMPONENT','1',NULL,NULL,NULL,NULL,'4');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_CHEMREAGENT','DATE_CREATED','Date','mm/dd/yyyy','10',NULL,NULL,'CHEM_C_COMPONENT','2',NULL,NULL,'T',NULL,'5');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_CHEMREAGENT','AMOUNT','Amount     ','99999999','8',NULL,NULL,'CHEM_C_COMPONENT','3','T','100','T',NULL,'6');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_CHEMREAGENT','UNITS','Units','!!!!','4','TV_CHEMUNIT',NULL,'CHEM_C_COMPONENT','4',NULL,'205','T',NULL,'7');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_CHEMREAGENT','COMMENTS','Comment',NULL,'2000',NULL,NULL,'CHEM_C_COMPONENT','5',NULL,NULL,NULL,'5',NULL);

DELETE FROM TV_DBPANEL WHERE PANEL_NAME = 'CHEM_C_SERVICEHISTORY';
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_INSTSTAT','STATUS_KEY','STATUS_KEY','99999999','9',NULL,'H','CHEM_C_SERVICEHISTORY','1',NULL,NULL,'F',NULL,'6');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_INSTSTAT','DATE_SERVICED','Date','mm/dd/yyyy','10',NULL,NULL,'CHEM_C_SERVICEHISTORY','2','T',NULL,'T',NULL,'1');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_INSTSTAT','TIME_SERVICED','Time','hh:mm','8',NULL,NULL,'CHEM_C_SERVICEHISTORY','3',NULL,'85','T',NULL,'2');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_INSTSTAT','SERVICED_BY','Serviced by','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX','50',NULL,NULL,'CHEM_C_SERVICEHISTORY','4','T','350','T',NULL,'3');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_INSTSTAT','TYPE_OF_SERVICE','Type','!!!!!!','6','TV_MAINTYPE',NULL,'CHEM_C_SERVICEHISTORY','5',NULL,'205','F',NULL,'4');
INSERT INTO TV_DBPANEL (TABLE_NAME,FIELD_NAME,PROMPT,EDIT_MASK,LENGTH,CODE_TABLE,REMOVE_FROM_SCREEN,PANEL_NAME,SEQUENCE,BUMP_NEXT_FIELD_UP,FIELD_DISPLAY_WIDTH,MANDATORY,MEMO_FIELD_LINES,TAB_ORDER) VALUES ('TV_INSTSTAT','COMMENTS','Comments',NULL,'2000',NULL,NULL,'CHEM_C_SERVICEHISTORY','6',NULL,'350','F','3','5');