SELECT 'm1   ' + dbo.PLC_NumberToBase64(CONTAINER_KEY) AS BARCODE, CONTAINER_KEY, CONTAINER_DESCRIPTION, C.* FROM TV_CONTAINER C  ORDER BY C.CONTAINER_KEY DESC

SELECT * FROM TV_WEBCONFIG WHERE CODE = 'BCCONTAINER_PAGE';