SELECT CONTAINER_KEY, PARENT_ECN, BARCODE, 
	(SELECT COUNT(EVIDENCE_CONTROL_NUMBER) FROM TV_LABITEM WHERE PARENT_ECN = I.EVIDENCE_CONTROL_NUMBER AND (BARCODE IS NULL OR BARCODE = '')) AS CHILDREN 
FROM TV_LABITEM I WHERE EVIDENCE_CONTROL_NUMBER