select LAB_CODE, USES_SUBMISSION_SEARCH from TV_LABCTRL2

TV_EXAMCODE.PRINT_CRYSTAL_REPORT_ONLY

select EXAM_CODE, PRINT_CRYSTAL_REPORT_ONLY from TV_EXAMCODE
where EXAM_CODE = 'FA'

update TV_EXAMCODE
set PRINT_CRYSTAL_REPORT_ONLY = 'T'
where EXAM_CODE = 'FA'

commit;

select LAB_CODE, USE_PIN_FOR_VERIFICATIONS from TV_LABCTRL5
where LAB_CODE = 'C'

update TV_LABCTRL5
set USE_PIN_FOR_VERIFICATIONS = 'F'
where LAB_CODE = 'C'


select * from TV_LABCTRL