SELECT "TV_LABITEM"."LAB_CASE_SUBMISSION", 
  "TV_LABITEM"."LAB_ITEM_NUMBER", 
  "TV_LABITEM"."ITEM_SORT", 
  "TV_LABITEM"."ITEM_DESCRIPTION", 
  "TV_LABITEM"."ITEM_TYPE", 
  "TV_LABITEM"."PACKAGING_CODE", 
  "TV_LABASSIGN"."SEQUENCE", 
  "TV_LABASSIGN"."SECTION", 
  "TV_LABITEM"."BARCODE", 
  "TV_LABCASE"."DEPARTMENT_CASE_NUMBER"
 FROM   ("VENTURA_DEV"."dbo"."TV_LABITEM" "TV_LABITEM" 
 INNER JOIN "VENTURA_DEV"."dbo"."TV_LABASSIGN" "TV_LABASSIGN" ON "TV_LABITEM"."CASE_KEY"="TV_LABASSIGN"."CASE_KEY") 
 INNER JOIN "VENTURA_DEV"."dbo"."TV_LABCASE" "TV_LABCASE" ON "TV_LABITEM"."CASE_KEY"="TV_LABCASE"."CASE_KEY"
 WHERE "TV_LABITEM".CASE_KEY = '2511'


-- EMPTY RESULT
 SELECT "TV_LABITEM"."LAB_CASE_SUBMISSION", 
  "TV_LABITEM"."LAB_ITEM_NUMBER", 
  "TV_LABITEM"."ITEM_SORT", 
  "TV_LABITEM"."ITEM_DESCRIPTION", 
  "TV_LABITEM"."ITEM_TYPE", 
  "TV_LABITEM"."PACKAGING_CODE", 
  "TV_LABASSIGN"."SEQUENCE", 
  "TV_LABASSIGN"."SECTION", 
  "TV_LABITEM"."BARCODE", 
  "TV_LABCASE"."DEPARTMENT_CASE_NUMBER"
 FROM   ("VENTURA_DEV"."dbo"."TV_LABITEM" "TV_LABITEM" 
 INNER JOIN "VENTURA_DEV"."dbo"."TV_LABASSIGN" "TV_LABASSIGN" ON "TV_LABITEM"."CASE_KEY"="TV_LABASSIGN"."CASE_KEY") 
 INNER JOIN "VENTURA_DEV"."dbo"."TV_LABCASE" "TV_LABCASE" ON "TV_LABITEM"."CASE_KEY"="TV_LABCASE"."CASE_KEY"
 WHERE "TV_LABITEM"."EVIDENCE_CONTROL_NUMBER" = '14907'