SELECT 
    A.SCHEDULE_KEY, 
    A.CASE_KEY, 
    A.DATE_RES, 
    B.DESCRIPTION, 
    C.NAME
FROM 
    TV_SCHEDULE A
    LEFT OUTER JOIN TV_SCHTYPE B ON B.TYPE_RES = A.TYPE_RES
    LEFT OUTER JOIN TV_ANALYST C ON C.ANALYST = A.ANALYST
WHERE 
    A.CASE_KEY = <&>CASE_KEY</&>;