-- ABQ Ticket #113485 - Item Info Additions for Case Correspondence

DELETE FROM TV_DBGRIDHD WHERE GRID_NAME = 'SCHEDULE';
INSERT INTO TV_DBGRIDHD (GRID_NAME,SQL_STRING,DESCRIPTION,PANEL_NAME,GRID_WIDTH,GRID_HEIGHT,RECORDS_PER_PAGE,USES_SCROLLBAR) VALUES ('SCHEDULE','SELECT
        A.SCHEDULE_KEY,
        A.CASE_KEY,
        TO_CHAR(A.DATE_RES, ''MM/DD/YYYY'') AS DATE_RES,
        TO_CHAR(A.TIME, ''HH24:MI:SS'') AS TIME,
        B.DESCRIPTION,
        C.NAME,
        A.COMMENTS,
        CASE 
            WHEN A.EVIDENCE_CONTROL_NUMBER IS NULL THEN 
                CASE
                    WHEN EXISTS (
                        SELECT 1
                        FROM TV_SCHDETL S
                        WHERE S.SCHEDULE_KEY = A.SCHEDULE_KEY
                    ) THEN
                        COALESCE(
                            (
                                SELECT LISTAGG(LI2.LAB_ITEM_NUMBER, '', '') 
                                       WITHIN GROUP (ORDER BY LI2.LAB_ITEM_NUMBER)
                                FROM TV_SCHDETL SD
                                LEFT JOIN TV_LABITEM LI2 
                                       ON LI2.EVIDENCE_CONTROL_NUMBER = SD.EVIDENCE_CONTROL_NUMBER
                                WHERE SD.SCHEDULE_KEY = A.SCHEDULE_KEY
                            ),
                            ''Deleted''
                        )
                    ELSE ''Not Item Related''
                END
            ELSE 
                COALESCE(I.LAB_ITEM_NUMBER, ''Deleted'')
        END AS ITEM_NUMBER,
        E.DESCRIPTION AS SECTION_DESCRIPTION
    FROM TV_SCHEDULE A
        LEFT JOIN TV_SCHTYPE B ON B.TYPE_RES = A.TYPE_RES
        LEFT JOIN TV_ANALYST C ON C.ANALYST = A.ANALYST
        LEFT JOIN TV_LABITEM I ON I.EVIDENCE_CONTROL_NUMBER = A.EVIDENCE_CONTROL_NUMBER
        LEFT JOIN TV_EXAMCODE E ON E.EXAM_CODE = A.SECTION
        LEFT JOIN TV_SCHDETL D ON D.SCHEDULE_KEY = A.SCHEDULE_KEY
    ORDER BY DATE_RES DESC, TIME DESC',
    'Schedule',NULL,'900',NULL,NULL,NULL);


DELETE FROM TV_DBGRIDDL WHERE GRID_NAME = 'SCHEDULE';
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('SCHEDULE','CASE_KEY','CASE_KEY','50','T','2',NULL,NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('SCHEDULE','DATE_RES','Date','100','F','3','DATE',NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('SCHEDULE','DESCRIPTION','Schedule Type','300','F','4',NULL,'WRAP:T',NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('SCHEDULE','ITEM_NUMBER','Item #','150','F','6',NULL,'WRAP:T',NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('SCHEDULE','NAME','User','200','F','5',NULL,'WRAP:T',NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('SCHEDULE','SCHEDULE_KEY','SCHEDULE_KEY','50','T','1',NULL,NULL,NULL);
INSERT INTO TV_DBGRIDDL (GRID_NAME,FIELD_NAME,FIELD_HEADER,FIELD_WIDTH,HIDE_FIELD,DISPLAY_ORDER,FIELD_TYPE,OPTIONS,PROMPT_CODE) VALUES ('SCHEDULE','SECTION_DESCRIPTION','Section','200','F','7',NULL,'WRAP:T',NULL);
