SELECT 
    C.CASE_KEY, 
    C.DEPARTMENT_CASE_NUMBER, 
    D.DEPARTMENT_NAME, 
    O.OFFENSE_DESCRIPTION AS CHARGE,  
    C.LAB_CASE,  C.OFFENSE_DATE 
FROM TV_LABCASE C 
INNER JOIN TV_DEPTNAME D ON C.DEPARTMENT_CODE = D.DEPARTMENT_CODE 
INNER JOIN TV_OFFENSE O ON C.OFFENSE_CODE = O.OFFENSE_CODE 
ORDER BY C.CASE_DATE DESC 
FETCH FIRST 10 ROWS ONLY;

